INSERT INTO `blogs` (`author`, `title`, `content`, `id`, `created_at`, `updated_at`, `postPic`) VALUES 
('ES', '', 'El verdadero poder no está en lo que puedes hacer, sino en lo que decides ser.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Cada amanecer es un nuevo hechizo para reinventarte.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El oro más valioso se encuentra en el corazón de los que sueñan.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El conocimiento es la chispa que enciende la llama de la sabiduría.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Un deseo sin acción es solo un sueño; actúa y verás la magia suceder.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El universo conspira a favor de aquellos que buscan la verdad con humildad.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Cada desafío es una oportunidad disfrazada de prueba.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La magia verdadera reside en el valor de enfrentar lo desconocido.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El futuro pertenece a quienes creen en la belleza de sus visiones.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'No busques fuera lo que ya tienes dentro: el poder de cambiar tu destino.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La paciencia es la alquimia que transforma la dificultad en fortaleza.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El amor es el ingrediente secreto en todas las pociones de éxito.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El coraje es la clave que abre las puertas de lo imposible.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'A veces, los caminos más oscuros llevan a los destinos más brillantes.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El conocimiento se multiplica cuando se comparte.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La fe en ti mismo es el conjuro más poderoso que puedes lanzar.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La sabiduría se cultiva con cada pregunta que te atreves a hacer.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El pasado es un pergamino, aprende de él, pero no te encadenes.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La creatividad es la varita mágica que transforma lo ordinario en extraordinario.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El respeto hacia los demás es el verdadero lenguaje universal de la magia.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Cada día es una nueva página en el gran libro de tu vida.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La gratitud es la magia que atrae más cosas buenas a tu vida.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El poder de una sonrisa puede iluminar incluso el corazón más sombrío.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La perseverancia es la piedra filosofal que convierte los sueños en realidad.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La verdad siempre encuentra su camino, como un río que fluye hacia el mar.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La magia de la vida está en aprender a bailar bajo la lluvia.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El equilibrio entre la mente y el corazón es la fórmula secreta de la paz interior.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Las palabras tienen poder; úsalas para construir, no para destruir.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El perdón es la magia que libera el alma y enciende la esperanza.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La intuición es la brújula interna que siempre te guiará hacia tu verdadero norte.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Cada acto de bondad es un hechizo que transforma el mundo.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El autoconocimiento es el elixir de la auténtica libertad.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'Los límites existen solo en la mente, atrévete a superarlos.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El presente es el único momento donde la magia de la vida ocurre.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La simplicidad es la clave de la verdadera grandeza.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La confianza en uno mismo es el primer paso hacia cualquier logro.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El respeto por la naturaleza es el respeto por nosotros mismos.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La vida es el mayor de los misterios, disfrútala con asombro y curiosidad.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'El amor propio es el primer capítulo de la historia del éxito.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('ES', '', 'La transformación personal es la magia que cambia el mundo desde dentro.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'True power lies not in what you can do, but in what you decide to be.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Each dawn is a new spell to reinvent yourself.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The most valuable gold is found in the hearts of those who dream.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Knowledge is the spark that ignites the flame of wisdom.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'A wish without action is just a dream; act and you will see the magic happen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The universe conspires in favor of those who seek the truth with humility.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Every challenge is an opportunity disguised as a test.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'True magic lies in the courage to face the unknown.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The future belongs to those who believe in the beauty of their visions.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Do not seek outside what you already have inside: the power to change your destiny.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Patience is the alchemy that transforms difficulty into strength.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Love is the secret ingredient in all success potions.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Courage is the key that opens the doors to the impossible.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Sometimes, the darkest paths lead to the brightest destinations.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Knowledge multiplies when it is shared.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Faith in yourself is the most powerful spell you can cast.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Wisdom is cultivated with every question you dare to ask.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The past is a scroll; learn from it, but do not be chained by it.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Creativity is the magic wand that transforms the ordinary into the extraordinary.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Respect for others is the true universal language of magic.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Every day is a new page in the great book of your life.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Gratitude is the magic that attracts more good things into your life.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The power of a smile can light up even the darkest heart.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Perseverance is the philosopher\'s stone that turns dreams into reality.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Truth always finds its way, like a river flowing to the sea.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The magic of life is in learning to dance in the rain.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The balance between mind and heart is the secret formula for inner peace.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Words have power; use them to build, not to destroy.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Forgiveness is the magic that frees the soul and ignites hope.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Intuition is the inner compass that will always guide you to your true north.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Every act of kindness is a spell that transforms the world.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Self-knowledge is the elixir of true freedom.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Limits exist only in the mind; dare to overcome them.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'The present is the only moment where the magic of life happens.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Simplicity is the key to true greatness.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Confidence in oneself is the first step toward any achievement.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Respect for nature is respect for ourselves.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Life is the greatest of mysteries; enjoy it with wonder and curiosity.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Self-love is the first chapter in the story of success.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('EN', '', 'Personal transformation is the magic that changes the world from within.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Wahre Macht liegt nicht in dem, was du tun kannst, sondern in dem, was du zu sein beschließt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Jeder Sonnenaufgang ist ein neuer Zauber, um dich neu zu erfinden.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Das wertvollste Gold findet man in den Herzen derer, die träumen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Wissen ist der Funke, der die Flamme der Weisheit entzündet.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Ein Wunsch ohne Handlung ist nur ein Traum; handle und du wirst die Magie sehen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Das Universum verschwört sich zugunsten derer, die die Wahrheit mit Demut suchen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Jede Herausforderung ist eine Gelegenheit, getarnt als Prüfung.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Wahre Magie liegt im Mut, dem Unbekannten entgegenzutreten.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Die Zukunft gehört denen, die an die Schönheit ihrer Visionen glauben.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Suche nicht draußen, was du bereits in dir hast: die Macht, dein Schicksal zu ändern.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Geduld ist die Alchemie, die Schwierigkeit in Stärke verwandelt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Liebe ist die geheime Zutat in allen Erfolgstränken.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Mut ist der Schlüssel, der die Türen zum Unmöglichen öffnet.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Manchmal führen die dunkelsten Wege zu den hellsten Zielen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Wissen vermehrt sich, wenn es geteilt wird.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Glaube an dich selbst ist der mächtigste Zauber, den du wirken kannst.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Weisheit wird mit jeder Frage kultiviert, die du zu stellen wagst.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Die Vergangenheit ist eine Schriftrolle; lerne von ihr, aber lass dich nicht fesseln.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Kreativität ist der Zauberstab, der das Gewöhnliche in das Außergewöhnliche verwandelt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Respekt vor anderen ist die wahre universelle Sprache der Magie.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Jeder Tag ist eine neue Seite im großen Buch deines Lebens.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Dankbarkeit ist die Magie, die mehr gute Dinge in dein Leben zieht.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Die Macht eines Lächelns kann selbst das dunkelste Herz erhellen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Ausdauer ist der Stein der Weisen, der Träume in Realität verwandelt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Wahrheit findet immer ihren Weg, wie ein Fluss zum Meer fließt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Die Magie des Lebens liegt darin, zu lernen, im Regen zu tanzen.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Das Gleichgewicht zwischen Geist und Herz ist die geheime Formel für inneren Frieden.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Worte haben Macht; nutze sie, um zu bauen, nicht um zu zerstören.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Vergebung ist die Magie, die die Seele befreit und Hoffnung entzündet.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Intuition ist der innere Kompass, der dich immer zu deinem wahren Norden führt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Jede Handlung der Freundlichkeit ist ein Zauber, der die Welt verwandelt.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Selbsterkenntnis ist der Elixier wahrer Freiheit.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Grenzen existieren nur im Kopf; wage es, sie zu überwinden.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Die Gegenwart ist der einzige Moment, in dem die Magie des Lebens geschieht.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Einfachheit ist der Schlüssel zu wahrer Größe.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Selbstvertrauen ist der erste Schritt zu jedem Erfolg.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Respekt vor der Natur ist Respekt vor uns selbst.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Das Leben ist das größte aller Geheimnisse; genieße es mit Staunen und Neugier.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Selbstliebe ist das erste Kapitel in der Geschichte des Erfolgs.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ''),
('DEU', '', 'Persönliche Transformation ist die Magie, die die Welt von innen heraus verändert.', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '');
